name: 'Create EAS Update'
description: 'Setup an expo project and create EAS update'
inputs:
  branch:
    description: 'Update branch.'
    required: true
  message:
    description: 'Update message.'
    required: false
    default: '${{ github.event.head_commit.message }}'
  expo-token:
    description: 'Expo authentication token'
    required: true
  npm-repository:
    description: 'NPM repository to authenticate against.'
    required: false
    default: 'https://artifactory.mersive.xyz/artifactory/api/npm/npm'
  npm-scope:
    description: 'NPM repository scope.'
    required: false
    default: '@mersive'
  npm-user:
    description: 'NPM username used for authentication.'
    required: true
  npm-pass:
    description: 'NPM password used for authentication.'
    required: true
  npm-email:
    description: 'NPM email used for authentication.'
    required: true
  lfs:
    description: 'Whether or not the repository uses LFS.'
    required: false
    default: 'false'
  node-version:
    description: 'What version of Node to use.'
    required: false
    default: '16.x'
runs:
  using: 'composite'
  steps:
    - name: Setup project
      uses: Mersive-Technologies/gh-actions/expo-setup@v1
      with:
        npm-user: ${{ inputs.npm-user }}
        npm-pass: ${{ inputs.npm-pass }}
        npm-email: ${{ inputs.npm-email }}
        lfs: true

    - name: Setup Expo and EAS
      uses: expo/expo-github-action@v7
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ inputs.expo-token }}

    - name: Create EAS update
      run: eas update --branch="${{ inputs.branch }}" --message="${{ inputs.message }}" --non-interactive
      shell: bash
